//<!--begin::Footer-->
document.write('<div class="footer d-flex flex-column flex-root" id="kt_footer">');    
    document.write('<div class="footer-mgmt bg-white d-flex flex-lg-column">');
        document.write('<div class="container py-4 d-flex flex-column flex-md-row align-items-center justify-content-between">');
            document.write('<div class="text-muted order-2 order-md-1">');
                document.write('<span class="font-weight-bold ml-2">고객지원센터</span>');
                document.write('<span class="ml-5 d-xl-inline-block">온라인 디지털 콘텐츠 산업발전법에 의한 표시</span>');
                document.write('<span class="ml-20 d-xl-block">대표전화 : 02-1234-5678 </span>');
                document.write('<span class="ml-20 d-xxl-inline-block d-xl-block">이메일</span>');
            document.write('</div>');
            document.write('<div class="text-muted order-2 order-md-1">');
                document.write('<span class="font-weight-bold ml-2">온라인 디지털 콘텐츠 산업발전법에 의한 표시</span>');
                document.write('<span class="ml-5 d-xl-inline-block">주소 : 서울특별시</span>');
                document.write('<span class="ml-20 d-xl-block">대표전화 : 02-1234-5678 </span>');
                document.write('<span class="ml-20 d-xxl-inline-block d-xl-block">이메일</span>');
            document.write('</div>');
            document.write('<div class="text-muted order-3 order-md-2">');
                document.write('<span class="font-weight-bold ml-2">설문조사 </span>');
                document.write('<span class="ml-5 d-xl-inline-block">주소 :  2007호</span>');
                document.write('<span class="ml-20 d-xl-block">대표전화 : 02-1234-5678 04142</span>');
                document.write('<span class="ml-20 d-xxl-inline-block d-xl-block">이메일 RIGHTS RESERVED</span>');
            document.write('</div>');
        document.write('</div>');
    document.write('</div>');
    document.write('<div class="footer-link bg-primary text-white py-2">');
        document.write('<div class="container link mb-0">');
            document.write('<a href="#" target="_blank" class="text-white">회사소개</a>');
            document.write('<a href="#" target="_blank" class="text-white">개인보호정책</a>');
            document.write('<a href="#" target="_blank" class="text-white">이용약관</a>');
            document.write('<a href="#" target="_blank" class="text-white">이메일 주소 무단수집거부</a>');
            document.write('<a href="#" target="_blank" class="text-white">공지사항</a>');
            document.write('<a href="#" target="_blank" class="text-white">고객지원</a>');
            document.write('<a href="#" target="_blank" class="text-white">유료옵션광고안내</a>');
        document.write('</div>');
    document.write('</div>');
    document.write('<div class="footer-mgmt bg-white d-flex flex-lg-column">');
        document.write('<div class="container py-4 d-flex flex-column flex-md-row align-items-center justify-content-between">');
            document.write('<div class="text-muted order-2 order-md-1">');
            document.write('<span class="font-weight-bold ml-2"><img alt="Logo" src="assets/media/logos/logo-letter-9.png" class="max-h-15px mr-5" />(주)호구153 주식회사 | </span>');
            document.write('<span class="ml-5 d-xl-inline-block">주소 : 서울특별시 서초구 논현로 87 삼호물산 빌딩 B동 2006호, 2007호</span>');
            document.write('<span class="ml-20 d-xl-block">대표전화 : 02-1234-5678 | 팩스 : 02-1234-1412 | 사업자등록번호 : 123-12-04142</span>');
            document.write('<span class="ml-20 d-xxl-inline-block d-xl-block">이메일 : <a href="mailto:admin@hogoo153.com">admin@hogoo153.com</a> | Copyright @ HOGOO 153 ALL RIGHTS RESERVED</span>');
            document.write('</div>');
        document.write('</div>');
    document.write('</div>');
document.write('</div>');
//<!--end::Footer-->